# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2019-03-16 11:00
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Catalog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, verbose_name='Name')),
                ('desc', models.CharField(max_length=1024, verbose_name='Description')),
                ('notes', models.CharField(blank=True, max_length=1024, verbose_name='Additional Notes')),
                ('active', models.BooleanField(default=True, help_text='Enable/Disable', verbose_name='Active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lendingcore_catalog_creator', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lendingcore_catalog_modifier', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Column',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, verbose_name='Name')),
                ('desc', models.CharField(max_length=1024, verbose_name='Description')),
                ('notes', models.CharField(blank=True, max_length=1024, verbose_name='Additional Notes')),
                ('active', models.BooleanField(default=True, help_text='Enable/Disable', verbose_name='Active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('catalog_id', models.IntegerField()),
                ('datasource_id', models.IntegerField()),
                ('data_type', models.CharField(choices=[('STRING', 'String'), ('TEXT', 'Text'), ('INT', 'Integer'), ('BIGINT', 'BigInteger'), ('FLOAT', 'Float'), ('DOUBLE', 'Double'), ('BLOB', 'Blob')], default='STRING', max_length=64)),
                ('position', models.IntegerField(default=1, verbose_name='Position')),
                ('deprecated', models.BooleanField(default=False, verbose_name='Deprecated')),
                ('restricted', models.BooleanField(default=False, help_text='See notes on nature of restrictions', verbose_name='Restricted Use')),
                ('permissions', models.BooleanField(default=False, verbose_name='Requires Permission')),
                ('sensitive', models.BooleanField(default=False, help_text='Has PII or Other Sensitive Information', verbose_name='Sensitive')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lendingcore_column_creator', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lendingcore_column_modifier', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True, help_text='Enable/Disable', verbose_name='Active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('klass', models.CharField(max_length=256, verbose_name='Class of object being commented upon')),
                ('name', models.CharField(max_length=256, verbose_name='Name of Feature')),
                ('owner', models.CharField(max_length=256, verbose_name='Owner of Feature')),
                ('comment', models.TextField(blank=True, max_length=1024, verbose_name='Comment')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lendingcore_comment_creator', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lendingcore_comment_modifier', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DataSource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, verbose_name='Name')),
                ('desc', models.CharField(max_length=1024, verbose_name='Description')),
                ('notes', models.CharField(blank=True, max_length=1024, verbose_name='Additional Notes')),
                ('active', models.BooleanField(default=True, help_text='Enable/Disable', verbose_name='Active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('catalog_id', models.IntegerField()),
                ('nature', models.CharField(choices=[('FS', 'Filesystem'), ('DB', 'Database'), ('BS', 'BlockStore')], default='BS', max_length=2)),
                ('url', models.CharField(max_length=1024, verbose_name='URI (Path or SQLAlchemy URL)')),
                ('sample', models.TextField(blank=True, max_length=10240)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lendingcore_datasource_creator', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lendingcore_datasource_modifier', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FeatureRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True, help_text='Enable/Disable', verbose_name='Active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(help_text='Name of feature', max_length=256, verbose_name='Name')),
                ('owner', models.CharField(help_text='Owner of feature', max_length=256, verbose_name='Owner')),
                ('desc', models.TextField(help_text='Summary of the feature', max_length=1024, verbose_name='Description')),
                ('status', models.CharField(choices=[('Open', 'Open'), ('Review', 'Review'), ('Closed', 'Closed')], default='Open', help_text='Status of the Request', max_length=32, verbose_name='Status')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lendingcore_featurerequest_creator', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lendingcore_featurerequest_modifier', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
