# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2019-08-14 06:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lendingcore', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='column',
            name='data_type',
            field=models.CharField(choices=[('TIMESTAMP', 'Timestamp'), ('DATE', 'Date'), ('DATETIME', 'DateTime'), ('ENUM', 'Enum'), ('CATEGORY', 'Category'), ('VARCHAR', 'Varchar'), ('STRING', 'String'), ('TEXT', 'Text'), ('LONGTEXT', 'LongText'), ('INT', 'Integer'), ('BIGINT', 'BigInteger'), ('FLOAT', 'Float'), ('DOUBLE', 'Double'), ('BLOB', 'Blob')], default='STRING', max_length=64),
        ),
    ]
