# Generated by Django 2.2.15 on 2021-12-29 16:12

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('lendingcore', '0007_role_visibilitymap'),
    ]

    operations = [
        migrations.AlterField(
            model_name='annotationmodel',
            name='dataset',
            field=jsonfield.fields.JSONField(default=[], help_text='A list of formatted entries that need labelling. See documentation', verbose_name='Dataset'),
        ),
        migrations.AlterField(
            model_name='annotationmodel',
            name='labels',
            field=jsonfield.fields.JSONField(default={}, help_text='A list of formatted labelling choices. See documentation', verbose_name='Labels'),
        ),
    ]
