# Generated by Django 2.2.15 on 2022-01-06 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lendingcore', '0008_auto_20211229_2142'),
    ]

    operations = [
        migrations.AlterField(
            model_name='column',
            name='data_type',
            field=models.CharField(choices=[('TIMESTAMP', 'Timestamp'), ('DATE', 'Date'), ('DATETIME', 'DateTime'), ('ENUM', 'Enum'), ('CATEGORY', 'Category'), ('VARCHAR', 'Varchar'), ('STRING', 'String'), ('TEXT', 'Text'), ('BOOL', 'Bool'), ('LONGTEXT', 'LongText'), ('INT', 'Integer'), ('BIGINT', 'BigInteger'), ('FLOAT', 'Float'), ('DOUBLE', 'Double'), ('BLOB', 'Blob')], default='STRING', max_length=64),
        ),
    ]
