# Generated by Django 2.2.15 on 2022-03-08 07:57

from django.db import migrations, models
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('lendingcore', '0009_auto_20220106_1249'),
    ]

    operations = [
        migrations.AddField(
            model_name='column',
            name='sample_raw',
            field=jsonfield.fields.JSONField(default=[], verbose_name='Raw data as JSON'),
        ),
        migrations.AddField(
            model_name='datasource',
            name='sample_raw',
            field=jsonfield.fields.JSONField(default=[], verbose_name='Raw data as JSON'),
        ),
        migrations.AddField(
            model_name='datasource',
            name='sql',
            field=models.TextField(default='', max_length=10240),
        ),
    ]
