# Generated by Django 2.2.15 on 2022-03-10 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lendingcore', '0010_auto_20220308_1327'),
    ]

    operations = [
        migrations.AddField(
            model_name='attachment',
            name='tags',
            field=models.CharField(blank=True, default='', max_length=128, verbose_name='Tags'),
        ),
        migrations.AddField(
            model_name='catalog',
            name='tags',
            field=models.CharField(blank=True, default='', max_length=128, verbose_name='Tags'),
        ),
        migrations.AddField(
            model_name='column',
            name='tags',
            field=models.CharField(blank=True, default='', max_length=128, verbose_name='Tags'),
        ),
        migrations.AddField(
            model_name='datasource',
            name='tags',
            field=models.CharField(blank=True, default='', max_length=128, verbose_name='Tags'),
        ),
        migrations.AddField(
            model_name='role',
            name='tags',
            field=models.CharField(blank=True, default='', max_length=128, verbose_name='Tags'),
        ),
    ]
