# Generated by Django 2.2.15 on 2022-04-12 06:07

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('lendingcore', '0011_auto_20220310_1143'),
    ]

    operations = [
        migrations.AddField(
            model_name='attachment',
            name='metadata',
            field=jsonfield.fields.JSONField(default={}, verbose_name='Metadata'),
        ),
        migrations.AddField(
            model_name='catalog',
            name='metadata',
            field=jsonfield.fields.JSONField(default={}, verbose_name='Metadata'),
        ),
        migrations.AddField(
            model_name='column',
            name='metadata',
            field=jsonfield.fields.JSONField(default={}, verbose_name='Metadata'),
        ),
        migrations.AddField(
            model_name='datasource',
            name='metadata',
            field=jsonfield.fields.JSONField(default={}, verbose_name='Metadata'),
        ),
        migrations.AddField(
            model_name='role',
            name='metadata',
            field=jsonfield.fields.JSONField(default={}, verbose_name='Metadata'),
        ),
    ]
