# Generated by Django 2.2.15 on 2022-04-12 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lendingcore', '0012_auto_20220412_1137'),
    ]

    operations = [
        migrations.AddField(
            model_name='attachment',
            name='humanized_name',
            field=models.CharField(blank=True, default='', max_length=256, verbose_name='Humanized Name'),
        ),
        migrations.AddField(
            model_name='catalog',
            name='humanized_name',
            field=models.CharField(blank=True, default='', max_length=256, verbose_name='Humanized Name'),
        ),
        migrations.AddField(
            model_name='column',
            name='humanized_name',
            field=models.CharField(blank=True, default='', max_length=256, verbose_name='Humanized Name'),
        ),
        migrations.AddField(
            model_name='datasource',
            name='humanized_name',
            field=models.CharField(blank=True, default='', max_length=256, verbose_name='Humanized Name'),
        ),
        migrations.AddField(
            model_name='role',
            name='humanized_name',
            field=models.CharField(blank=True, default='', max_length=256, verbose_name='Humanized Name'),
        ),
    ]
